name: Node CI

on:
  pull_request:
    branches:
    - master

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        node: [14.18.0, 16.14.0, 18.0.0]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test
      env:
        GIT_AUTHOR_NAME: GitHub Actions
        GIT_AUTHOR_EMAIL: noreply@example.com
        GIT_COMMITTER_NAME: GitHub Actions
        GIT_COMMITTER_EMAIL: noreply@example.com
